const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
const ADD_CART = "ADD_CART";
const DELETE_CART = "DELETE_CART";

export {
    GET_PRODUCT_LOADING, GET_PRODUCT_SUCCESS, GET_PRODUCT_FAILURE, ADD_CART, DELETE_CART,
};
